services:
  db:
    image: mysql:8.0.22
    container_name: mysql_eam
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    hostname: db
    networks:
      - eam_apps
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: spring_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SPRING_APP_PORT}:${SPRING_APP_PORT}"
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APP_NAME}
      SERVER_PORT: ${SPRING_APP_PORT}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    networks:
      - eam_apps

  nginx:
    image: nginx:latest
    container_name: nginx_eam
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - eam_apps

  adminer:
    image: adminer
    container_name: adminer_eam
    restart: always
    ports:
      - 8000:8080
    networks:
      - eam_apps
    depends_on:
      db:
        condition: service_healthy

networks:
  eam_apps:
    driver: bridge

volumes:
  mysql_data:
