services:
  db:
    image: mysql:8.0.22
    container_name: mysql_eam
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    hostname: db
    networks:
      - eam_apps
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer_eam
    restart: always
    ports:
      - 8000:8080
    networks:
      - eam_apps
    depends_on:
      db:
        condition: service_healthy

networks:
  eam_apps:
    driver: bridge

volumes:
  mysql_data:
