spring:
  application:
    name: hospital_api

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_api?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 2320183A6A5FB
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Opciones: create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  springdoc:
    api-docs:
      enabled: true

    swagger-ui:
      enabled: true
      path: /swagger-ui.html

logging:
  level:
    org.springframework: DEBUG

server:
  port: 4500
